# Generated by Django 4.0.2 on 2022-11-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('addition', 'addition'), ('subtraction', 'subtraction'), ('multiplication', 'multiplication')], default='+', max_length=14)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('slackUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
