# Generated by Django 4.0.2 on 2022-11-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='slackUsername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
