# Generated by Django 4.0.2 on 2022-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_operations_slackusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='operation_type',
            field=models.CharField(max_length=20),
        ),
    ]
